#!/bin/sh

#bin/local-php-security-checker composer.lock

bin/php vendor/bin/phpcbf --standard=PSR12 ./src ./tests
bin/php vendor/bin/phpcs --standard=PSR12 ./src ./tests

bin/php vendor/bin/phpstan analyse --level=9 ./src
bin/php vendor/bin/phpstan analyse --level=9 ./tests

bin/phpunit --testsuite all
